version = 1

[global]
experimental_fps_limit = 120
experimental_present_mode = true
flow_scale = 1
multiplier = 3
performance_mode = true

[[game]]
exe = "vkcube"
experimental_fps_limit = 120
experimental_present_mode = true
flow_scale = 1
multiplier = 3
performance_mode = true

[[game]]
exe = "Subnautica.exe"
experimental_fps_limit = 120
experimental_present_mode = true
flow_scale = 1
multiplier = 2
performance_mode = true

[[game]]
exe = "ff7rebirth.exe"
experimental_fps_limit = 120
experimental_present_mode = true
flow_scale = 1
multiplier = 2
performance_mode = true

[[game]]
exe = "OblivionRemastered.exe"
experimental_fps_limit = 120
experimental_present_mode = true
flow_scale = 1
multiplier = 2
performance_mode = true

# [[game]] # example entry
# exe = "Game.exe"
# env = "SteamDeck=0"
#
# multiplier = 3
# flow_scale = 0.7
# performance_mode = true
# hdr_mode = false
#
# experimental_present_mode = fifo
# experimental_fps_limit = 48
